/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allil
 */
public class ContenidoDocente extends javax.swing.JFrame {
    private String id;
    private int filaSeleccionada = -1;
    
    public ContenidoDocente(String id) throws FileNotFoundException {
        initComponents();
        this.setResizable(false); // Hace que la ventana no sea redimensionable
        this.setLocationRelativeTo(null);//para que la interfaz aparezca en el centro
        this.setTitle("Agregar Contenido"); // Establece el título de la ventana
        this.id = id;
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/Logo1.png"));
        this.setIconImage(icono.getImage());
        
        
        Icon iconDevolver = setIcono("/img/devolver.png", 46, 41);
        btnDevolver.setIcon(iconDevolver);
        
       
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                filaSeleccionada = jTable1.getSelectedRow();
                if (filaSeleccionada != -1) {
                    String codigo = jTable1.getValueAt(filaSeleccionada, 0).toString();
                    String tema = jTable1.getValueAt(filaSeleccionada, 1).toString();
                    String tarea = jTable1.getValueAt(filaSeleccionada, 2).toString();

                    txtCodC.setText(codigo);
                    txtTema.setText(tema);
                }
            }
        });

        
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                filaSeleccionada = jTable1.getSelectedRow();
                int columnaDocumento = 2; // La columna que contiene el nombre del documento en tu modelo de datos

                if (filaSeleccionada != -1 && e.getClickCount() == 2) {
                    String nombreDocumento = jTable1.getValueAt(filaSeleccionada, columnaDocumento).toString();
                    abrirDocumentoDesdeTabla(nombreDocumento);
                }
            }
        });


        DefaultTableModel mdlTabla = actualizarDatos();
        if (mdlTabla != null) {
            jTable1.setModel(mdlTabla);
        } else {
            System.err.println("El método actualizarDatos() devolvió un modelo de tabla nulo.");
        }
  
        
    }

    private ContenidoDocente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblFe = new javax.swing.JLabel();
        txtCodC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtTema = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFe.setFont(new java.awt.Font("Rockwell", 0, 19)); // NOI18N
        lblFe.setText("TEMA:");
        jPanel1.add(lblFe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 138, 33));

        txtCodC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodCActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, 30));

        jButton1.setBackground(new java.awt.Color(55, 100, 121));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Subir archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 120, 30));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 360, 160));

        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 50, 60));

        btnEditar.setContentAreaFilled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 42, 70));
        jPanel1.add(txtTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 120, 30));

        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 46, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoContenido.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int seleccion;

        String codigo = txtCodC.getText().trim();
        String tema = txtTema.getText().trim();

        // Validar que el código del curso tenga exactamente 4 dígitos numéricos
        if (codigo.length() != 4 || !codigo.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "El código del curso debe tener exactamente 4 dígitos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar si el curso existe
        if (!existeCurso(codigo)) {
            JOptionPane.showMessageDialog(this, "El código del curso no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            txtCodC.setText("");
            return;
        }

        // Validar que se haya ingresado texto en el campo de tema y que solo sean letras
        if (tema.isEmpty() || !tema.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un tema válido con solo letras.", "Error", JOptionPane.ERROR_MESSAGE);
            txtTema.setText("");
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF y Word", "pdf", "doc", "docx");
        fileChooser.setFileFilter(filter);
        seleccion = fileChooser.showOpenDialog(this);

        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int filaSeleccionada = jTable1.getSelectedRow();
                if (filaSeleccionada != -1) {
                    String codigo = jTable1.getValueAt(filaSeleccionada, 0).toString();
                    String tema = jTable1.getValueAt(filaSeleccionada, 1).toString();

                    txtCodC.setText(codigo);
                    txtTema.setText(tema);
                }
            }
        });

        guardarInformacionEnArchivo(codigo, tema, fileChooser.getSelectedFile().getAbsolutePath());
        try {
            DefaultTableModel mdlTabla = actualizarDatos(); 
            jTable1.setModel(mdlTabla); 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ContenidoDocente.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Contenido agregado correctamente.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed



    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (filaSeleccionada != -1) {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            String codigo = modelo.getValueAt(filaSeleccionada, 0).toString();
            String tema = modelo.getValueAt(filaSeleccionada, 1).toString();
            String tarea = modelo.getValueAt(filaSeleccionada, 2).toString();

            // Eliminar la fila de la tabla
            modelo.removeRow(filaSeleccionada);
            txtTema.setText("");
            txtCodC.setText("");
            JOptionPane.showMessageDialog(this, "Contenido eliminado correctamente.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);



            actualizarTxt(codigo, tema, tarea);
            } else {
                JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    public void actualizarTxt(String codigo, String tema, String tarea) {
        try {
            File inFile = new File("TareasTemp.txt");
            File outFile = new File("Tareas.txt");

            BufferedReader br = new BufferedReader(new FileReader(inFile));
            BufferedWriter bw = new BufferedWriter(new FileWriter(outFile));

            String line;
            while ((line = br.readLine()) != null) {
                String[] datos = line.split(";");
                if (datos.length >= 4) {
                    String codigoTarea = datos[0];
                    if (!codigoTarea.equals(codigo) || !datos[1].equals(tema) || !datos[2].equals(tarea)) {
                        bw.write(line);
                        bw.newLine();
                    }
                }
            }

            br.close();
            bw.close();
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Hubo un error al actualizar el archivo.");
        }
    }



    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        txtCodC.setEditable(false);

        // Verifica si se seleccionó una fila para editar
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para editar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Obtén los valores actuales de la fila seleccionada
        String codigo = modelo.getValueAt(filaSeleccionada, 0).toString();
        String tema = modelo.getValueAt(filaSeleccionada, 1).toString();
        String tarea = modelo.getValueAt(filaSeleccionada, 2).toString();

        // Verifica si el contenido del campo de tema ha cambiado
        if (!txtTema.getText().equals(tema)) {
            // Si ha cambiado, actualiza el valor en el modelo de la tabla
            modelo.setValueAt(txtTema.getText(), filaSeleccionada, 1);

            // Actualiza el archivo "Tareas.txt" con los nuevos datos y la tabla
            actualizarArchivoYTabla(true, false);

            JOptionPane.showMessageDialog(this, "Contenido editado correctamente.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Si no ha cambiado, muestra un mensaje informativo
            JOptionPane.showMessageDialog(this, "No se realizaron cambios.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }



    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        PDocente frame = new PDocente(id);
        frame.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnDevolverActionPerformed

    private void actualizarArchivoYTabla(boolean actualizarEnArchivo, boolean actualizarEnTabla) {
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

    try {
        FileWriter fw = new FileWriter("Tareas.txt");
        BufferedWriter bw = new BufferedWriter(fw);

        // Recorre las filas de la tabla y guarda los datos en el archivo
        for (int i = 0; i < modelo.getRowCount(); i++) {
            for (int j = 0; j < modelo.getColumnCount(); j++) {
                if (j == 1) {
                    // Si es la columna de tema, verifica si la fila está siendo editada
                    if (i == filaSeleccionada && actualizarEnArchivo) {
                        // Si es la fila en edición, escribe el nuevo valor del campo de tema
                        bw.write(txtTema.getText());
                    } else {
                        // Si no es la fila en edición, escribe el valor actual de la celda
                        bw.write(modelo.getValueAt(i, j).toString());
                    }
                } else {
                    bw.write(modelo.getValueAt(i, j).toString());
                }
                bw.write(";");
            }
            bw.newLine();
        }

        bw.close();
        fw.close();

        if (actualizarEnTabla) {
            // Si se debe actualizar en la tabla, vuelve a cargar los datos desde el archivo
            DefaultTableModel mdlTabla = actualizarDatos();
            jTable1.setModel(mdlTabla);
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
}


    
    public boolean existeCurso(String courseCode) {
        try {
            BufferedReader br = new BufferedReader(new FileReader("curso.txt"));
            String line;

            while ((line = br.readLine()) != null) {
                String[] datos = line.split(";");
                if (datos.length >= 3) {
                    String code = datos[0];

                        if (courseCode.equals(code)) {
                        br.close();
                        return true; 
                    }
                }
            }

            br.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    return false;  
    }
    
    private void abrirDocumentoDesdeTabla(String rutaCompleta) {
        try {
            abrirArchivo(rutaCompleta);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al abrir el documento: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void abrirArchivo(String rutaCompleta) throws IOException {
        File archivo = new File(rutaCompleta);

        if (archivo.exists()) {
            Desktop.getDesktop().open(archivo);
        } else {
            JOptionPane.showMessageDialog(this, "El archivo no existe: " + rutaCompleta, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void guardarInformacionEnArchivo(String codigo, String tema, String nombreArchivo) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("Tareas.txt", true))) {
            File archivoSeleccionado = new File(nombreArchivo);
            String rutaCompleta = archivoSeleccionado.getAbsolutePath();
            writer.write(codigo + ";" + tema + ";" + rutaCompleta);
            writer.newLine();
        } catch (IOException e) {
            System.err.println("Error al escribir en el archivo: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    //Método para actualizar los datos en la tabla
    public DefaultTableModel actualizarDatos() throws FileNotFoundException {
        Vector cabeceras = new Vector();
        cabeceras.addElement("Código");
        cabeceras.addElement("Tema");
        cabeceras.addElement("Doc");

        DefaultTableModel mdlTabla = new DefaultTableModel(cabeceras, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            FileReader fr = new FileReader("Tareas.txt");
            BufferedReader br = new BufferedReader(fr);
            String d;
            while ((d = br.readLine()) != null) {
                StringTokenizer dato = new StringTokenizer(d, ";");
                Vector x = new Vector();
                while (dato.hasMoreTokens()) {
                    x.addElement(dato.nextToken());
                }
                mdlTabla.addRow(x);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return mdlTabla;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContenidoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContenidoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContenidoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContenidoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContenidoDocente().setVisible(true);
            }
        });
    }
    public Icon setIcono(String ulr, int ancho, int alto) {
        ImageIcon icon = new ImageIcon(getClass().getResource(ulr));
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblFe;
    private javax.swing.JTextField txtCodC;
    private javax.swing.JTextField txtTema;
    // End of variables declaration//GEN-END:variables


}
