/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Melany Suarez
 */
public class PDocente extends javax.swing.JFrame {
    private String id;
    private JLabel mensajeLabel;
    private Timer timer;
    private String[] mensajes = {
       "Un buen maestro puede inspirar esperanza, despertar la imaginación e inculcar el amor por el aprendizaje.\" - Brad Henry",
        "La enseñanza es la profesión que crea todas las demás profesiones.\" - Desconocido",
        "El objetivo de la educación es reemplazar una mente vacía por una mente abierta.\" - Malcolm Forbes",
        "Un maestro afecta la eternidad; nunca se puede decir dónde termina su influencia.\" - Henry Adams",
        "La educación no es llenar un cubo, sino encender un fuego.\" - William Butler Yeats",
        "El mayor signo de éxito para un maestro es poder decir: 'Los niños están trabajando como si yo no existiera'.\" - Maria Montessori",
        "La paciencia y la perseverancia tienen un efecto mágico antes el cual las dificultades desaparecen y los obstáculos se desvanecen.\" - John Quincy Adams",
        "El aula debe ser un escenario donde los sueños cobran vida.\" - Oprah Winfrey",
        "La educación es el pasaporte hacia el futuro, el mañana pertenece a aquellos que se preparan para él hoy.\" - Malcolm X",
        "Enseñar no es transferir conocimiento, sino crear las posibilidades para su propia producción o construcción.\" - Paulo Freire",
        "El educador no es el que provee la información, sino el que despierta la inteligencia en el estudiante.\" - Albert Einstein",
        "Ser un docente significa ser el arquitecto del futuro.\" - Sócrates" 
    };
    private int mensajeActual;
    /**
     * Creates new form PrincipalDocente
     */
    public PDocente(String id) {
        initComponents();
        this.setResizable(false); // Hace que la ventana no sea redimensionable
        this.setLocationRelativeTo(null);//para que la interfaz aparezca en el centro
        this.setTitle("Ventana Docente"); // Establece el título de la ventana
        this.id = id;  // Asigna el ID del usuario
        
        // Agrega el JLabel al jPanel2

        Icon iconCS = setIcono("/img/cerrar-sesion.png", 39, 39);
        btn_Cerrar.setIcon(iconCS);
        
        
        timer = new Timer(5000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cambiarMensaje();
            }
        });
        timer.start();
         // Cargar una imagen como icono desde el paquete "img" y establecerla en la ventana
        ImageIcon icono = new ImageIcon(getClass().getResource("/img/Logo1.png"));
        this.setIconImage(icono.getImage());
        
        
        
    }

    private PDocente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void cambiarMensaje() {
    jLabel1.setText(StrToHtml(mensajes[mensajeActual]));
    mensajeActual = (mensajeActual + 1) % mensajes.length;
    
    }
    public String StrToHtml(String mensajes){
        return "<html><p>" + mensajes + "</p><html>";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPerfil1 = new javax.swing.JButton();
        btn_Curso = new javax.swing.JButton();
        btnCD = new javax.swing.JButton();
        btn_TA = new javax.swing.JButton();
        btn_Cerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerfil1.setContentAreaFilled(false);
        btnPerfil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfil1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 170, 140));

        btn_Curso.setContentAreaFilled(false);
        btn_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CursoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 160, 140));

        btnCD.setContentAreaFilled(false);
        btnCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCDActionPerformed(evt);
            }
        });
        jPanel1.add(btnCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 160, 140));

        btn_TA.setContentAreaFilled(false);
        btn_TA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TAActionPerformed(evt);
            }
        });
        jPanel1.add(btn_TA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 150, 130));

        btn_Cerrar.setBorder(null);
        btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 50, 50));

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        jLabel1.setText("Bienvenidos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 430, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PDoc.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CursoActionPerformed
        VentanaCursoDocente frame = new VentanaCursoDocente(id);
        frame.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_btn_CursoActionPerformed

    private void btnPerfil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfil1ActionPerformed
Perfil frame = new Perfil(id);
        frame.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_btnPerfil1ActionPerformed

    private void btnCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCDActionPerformed
try {
            ContenidoDocente frame = new ContenidoDocente(id);
            frame.setVisible(true);
            this.setVisible(false);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PDocente.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_btnCDActionPerformed

    private void btn_TAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TAActionPerformed
        Tarea frame = new Tarea(id);
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TAActionPerformed

    private void btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CerrarActionPerformed
         // TODO add your handling code here:
        Object[] options = {"Sí", "Cancelar"};
        int choice = JOptionPane.showOptionDialog(this, "¿Estás seguro de cerrar sesión?", "Confirmación",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (choice == 0) { // El índice 0 corresponde a "Sí"
            Login newframe = new Login();
            newframe.setVisible(true);
            this.setVisible(false);
        } else if (choice == 1) { // El índice 1 corresponde a "Cancelar"
            // Realiza las acciones correspondientes si el usuario elige "Cancelar"
        }
    }//GEN-LAST:event_btn_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public Icon setIcono(String ulr, int ancho, int alto) {
        ImageIcon icon = new ImageIcon(getClass().getResource(ulr));
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCD;
    private javax.swing.JButton btnPerfil1;
    private javax.swing.JButton btn_Cerrar;
    private javax.swing.JButton btn_Curso;
    private javax.swing.JButton btn_TA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
