/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Melany Suarez
 */
public class PerfilEst extends javax.swing.JFrame {
    private String idEst;
    private String id;
    private String courseName;
    /**
     * Creates new form PerfilEst
     */

    public PerfilEst(String id,String courseName, String idEst) {
        initComponents();
        this.id = id;
        this.courseName = courseName;
        this.idEst = idEst;  // Asigna el ID del usuario
        
        BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader("Estudiante.txt"));
            String[] datos = cargarDatosUsuario(br);

            // Concatena el nombre del estudiante al título de la ventana
            this.setTitle("Perfil estudiante - " + datos[0]);

            this.setResizable(false);
            this.setLocationRelativeTo(null);
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Cierra solo la ventana de ejercicios al presionar el botón Cerrar
            ImageIcon icono = new ImageIcon(getClass().getResource("/img/Logo1.png"));
            this.setIconImage(icono.getImage());
            

            cargarImagenUsuario();  // Llama al método para cargar los datos del usuario
            revalidate();
            repaint();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    private PerfilEst() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_ImgUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(360, 440));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre:");
        jPanel3.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, -1));

        Correo.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Correo.setText("Correo:");
        jPanel3.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 160, -1));

        Id.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Id.setText("Documento:");
        jPanel3.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DATOS ESTUDIANTE");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, -1));

        lbl_ImgUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ImgUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel3.add(lbl_ImgUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 147, 106));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 240, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoPerfil.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    public String[] cargarDatosUsuario(BufferedReader br) throws IOException {
        String linea;
        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");
            if (datos.length >= 2 && datos[2].equals(idEst)) {
                String nom = datos[0];
                String ap = datos[1];
                Nombre.setText(nom + " " + ap);
                Correo.setText(datos[3]);
                Id.setText("CC. " + datos[2]);

                cargarImagenUsuario();
                return new String[]{nom + " " + ap};  // Devuelve el nombre del estudiante
            }
        }
        return new String[]{""};  // Devuelve un array vacío si no se encuentra el estudiante
    }
    
     public void cargarImagenUsuario() {
        try {
            BufferedReader br = new BufferedReader(new FileReader("imgUsuario.txt"));
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] datosImg = linea.split(";");
                if (datosImg.length == 2 && datosImg[0].equals(idEst)) {
                    String rutaImagen = datosImg[1];
                    mostrarImagenUsuario(rutaImagen);
                    break;
                }
            }
            br.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
     public void mostrarImagenUsuario(String rutaImagen) {
        ImageIcon icono = new ImageIcon(rutaImagen);
        Image img = icono.getImage().getScaledInstance(lbl_ImgUsuario.getWidth(), lbl_ImgUsuario.getHeight(), Image.SCALE_SMOOTH);
        lbl_ImgUsuario.setText(null);
        lbl_ImgUsuario.setIcon(new ImageIcon(img));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            PerfilEst Vframe = new PerfilEst();
                Vframe.setVisible(true);               
            }
        });
    }
    
      public Icon setIcono(String ulr, int ancho, int alto) {
        ImageIcon icon = new ImageIcon(getClass().getResource(ulr));
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_ImgUsuario;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
